spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/jpa_transactional_demo_db
    username: jpa_transactional_demo_user
    password: jpa_transactional_demo_pass
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
#    show-sql: true
    open-in-view: true
    properties:
#      hibernate.generate_statistics: true
#      hibernate.format_sql: true
      hibernate.ddl-auto: none
      hibernate.connection.provider_disables_autocommit: true
      hibernate.temp.use_jdbc_metadata_defaults: false # to avoid `Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.`
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.jdbc.time_zone: UTC
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
  mvc:
    servlet:
      load-on-startup: 1

logging:
  level:
    net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener: DEBUG