
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpaTransactionalDemo
    username: jpaTransactionalDemo
    password:
  jpa:
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.ddl-auto: none